### ISSUE TITLE
[Bug] The plugin don't load with Banner

### ISSUE THREAD

**Issue by Smaillor** [ToberoCat/ImprovedFactions#203]
**Describe the bug**
The plugin just won't load with Banner and a large error message appear in the console.

**ERROR FROM THE CONSOLE :**
[12:10:45] [Server thread/INFO]: [ImprovedFactions] Enabling ImprovedFactions v2.2.0
[12:10:45] [Server thread/ERROR]: Error occurred while enabling ImprovedFactions v2.2.0 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at net.kyori.adventure.platform.bukkit.CraftBukkitFacet$Chat1_19_3.isSupported(CraftBukkitFacet.java:309) ~[?:?]
        at net.kyori.adventure.platform.facet.Facet.of(Facet.java:79) ~[?:?]
        at net.kyori.adventure.platform.bukkit.BukkitAudience.<clinit>(BukkitAudience.java:44) ~[?:?]
        at net.kyori.adventure.platform.bukkit.BukkitAudiencesImpl.createAudience(BukkitAudiencesImpl.java:132) ~[?:?]
        at net.kyori.adventure.platform.bukkit.BukkitAudiencesImpl.createAudience(BukkitAudiencesImpl.java:74) ~[?:?]
        at net.kyori.adventure.platform.facet.FacetAudienceProvider.lambda$addViewer$0(FacetAudienceProvider.java:112) ~[?:?]
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[?:?]
        at net.kyori.adventure.platform.facet.FacetAudienceProvider.addViewer(FacetAudienceProvider.java:110) ~[?:?]
        at net.kyori.adventure.platform.bukkit.BukkitAudiencesImpl.<init>(BukkitAudiencesImpl.java:99) ~[?:?]
        at net.kyori.adventure.platform.bukkit.BukkitAudiencesImpl$Builder.lambda$build$1(BukkitAudiencesImpl.java:171) ~[?:?]
        at java.util.HashMap.computeIfAbsent(HashMap.java:1228) ~[?:?]
        at java.util.Collections$SynchronizedMap.computeIfAbsent(Collections.java:2760) ~[?:?]
        at net.kyori.adventure.platform.bukkit.BukkitAudiencesImpl$Builder.build(BukkitAudiencesImpl.java:169) ~[?:?]
        at net.kyori.adventure.platform.bukkit.BukkitAudiencesImpl.instanceFor(BukkitAudiencesImpl.java:89) ~[?:?]
        at net.kyori.adventure.platform.bukkit.BukkitAudiences.create(BukkitAudiences.java:53) ~[?:?]
        at io.github.toberocat.improvedfactions.ImprovedFactionsPlugin.onEnable(ImprovedFactionsPlugin.kt:67) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267) ~[banner-1.20.1-608-server.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) ~[banner-1.20.1-608-server.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:482) ~[banner-1.20.1-608-server.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:537) ~[banner-1.20.1-608-server.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:459) ~[banner-1.20.1-608-server.jar:?]
        at net.minecraft.server.MinecraftServer.handler$zca000$banner$enablePlugins(MinecraftServer.java:2208) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:339) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3823(class_3176.java:169) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:2061) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1927 failed
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.16.0.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.16.0.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.0.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.0.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?]
        at java.lang.Class.privateGetDeclaredMethods(Class.java:3458) ~[?:?]
        at java.lang.Class.privateGetPublicMethods(Class.java:3483) ~[?:?]
        at java.lang.Class.privateGetPublicMethods(Class.java:3489) ~[?:?]
        at java.lang.Class.privateGetPublicMethods(Class.java:3489) ~[?:?]
        at java.lang.Class.privateGetPublicMethods(Class.java:3489) ~[?:?]
        at java.lang.Class.getMethods(Class.java:2068) ~[?:?]
        at com.mohistmc.banner.bukkit.remapping.ClassLoaderRemapper.tryGetMethods(ClassLoaderRemapper.java:109) ~[banner-1.20.1-608-server.jar:?]
        at com.mohistmc.banner.bukkit.remapping.ClassLoaderRemapper.lambda$getMethods$0(ClassLoaderRemapper.java:102) ~[banner-1.20.1-608-server.jar:?]
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1740) ~[?:?]
        at com.mohistmc.banner.bukkit.remapping.ClassLoaderRemapper.getMethods(ClassLoaderRemapper.java:102) ~[banner-1.20.1-608-server.jar:?]
        at com.mohistmc.banner.bukkit.remapping.ClassLoaderRemapper.tryMapMethodToSrg(ClassLoaderRemapper.java:223) ~[banner-1.20.1-608-server.jar:?]
        at com.mohistmc.banner.bukkit.remapping.ReflectionHandler_6.handleLookupFindStatic(ReflectionHandler.java:304) ~[banner-1.20.1-608-server.jar:?]
        at com.mohistmc.banner.bukkit.remapping.ReflectionHandler_6.handleLookupFindVirtual(ReflectionHandler.java:320) ~[banner-1.20.1-608-server.jar:?]
        at net.kyori.adventure.platform.bukkit.MinecraftReflection.searchMethod(MinecraftReflection.java:182) ~[?:?]
        at net.kyori.adventure.platform.bukkit.MinecraftReflection.searchMethod(MinecraftReflection.java:157) ~[?:?]
        at net.kyori.adventure.platform.bukkit.CraftBukkitAccess$Chat1_19_3.<clinit>(CraftBukkitAccess.java:95) ~[?:?]
        ... 27 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.15.0+mixin.0.8.7.jar:0.15.0+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.15.0+mixin.0.8.7.jar:0.15.0+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.15.0+mixin.0.8.7.jar:0.15.0+mixin.0.8.7]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.16.0.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.16.0.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.0.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.0.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?]
        at java.lang.Class.privateGetDeclaredMethods(Class.java:3458) ~[?:?]
        at java.lang.Class.privateGetPublicMethods(Class.java:3483) ~[?:?]
        at java.lang.Class.privateGetPublicMethods(Class.java:3489) ~[?:?]
        at java.lang.Class.privateGetPublicMethods(Class.java:3489) ~[?:?]
        at java.lang.Class.privateGetPublicMethods(Class.java:3489) ~[?:?]
        at java.lang.Class.getMethods(Class.java:2068) ~[?:?]
        at com.mohistmc.banner.bukkit.remapping.ClassLoaderRemapper.tryGetMethods(ClassLoaderRemapper.java:109) ~[banner-1.20.1-608-server.jar:?]
        at com.mohistmc.banner.bukkit.remapping.ClassLoaderRemapper.lambda$getMethods$0(ClassLoaderRemapper.java:102) ~[banner-1.20.1-608-server.jar:?]
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1740) ~[?:?]
        at com.mohistmc.banner.bukkit.remapping.ClassLoaderRemapper.getMethods(ClassLoaderRemapper.java:102) ~[banner-1.20.1-608-server.jar:?]
        at com.mohistmc.banner.bukkit.remapping.ClassLoaderRemapper.tryMapMethodToSrg(ClassLoaderRemapper.java:223) ~[banner-1.20.1-608-server.jar:?]
        at com.mohistmc.banner.bukkit.remapping.ReflectionHandler_6.handleLookupFindStatic(ReflectionHandler.java:304) ~[banner-1.20.1-608-server.jar:?]
        at com.mohistmc.banner.bukkit.remapping.ReflectionHandler_6.handleLookupFindVirtual(ReflectionHandler.java:320) ~[banner-1.20.1-608-server.jar:?]
        at net.kyori.adventure.platform.bukkit.MinecraftReflection.searchMethod(MinecraftReflection.java:182) ~[?:?]
        at net.kyori.adventure.platform.bukkit.MinecraftReflection.searchMethod(MinecraftReflection.java:157) ~[?:?]
        at net.kyori.adventure.platform.bukkit.CraftBukkitAccess$Chat1_19_3.<clinit>(CraftBukkitAccess.java:95) ~[?:?]
        ... 27 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Constant modifier method skipLoop(I)I in lithium.mixins.json:world.explosions.ExplosionMixin from mod lithium failed injection check, (0/1) succeeded. Scanned 0 target(s). Using refmap mixins.lithium.refmap.json
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:531) ~[sponge-mixin-0.15.0+mixin.0.8.7.jar:0.15.0+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1490) ~[sponge-mixin-0.15.0+mixin.0.8.7.jar:0.15.0+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:752) ~[sponge-mixin-0.15.0+mixin.0.8.7.jar:0.15.0+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:330) ~[sponge-mixin-0.15.0+mixin.0.8.7.jar:0.15.0+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:246) ~[sponge-mixin-0.15.0+mixin.0.8.7.jar:0.15.0+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:437) ~[sponge-mixin-0.15.0+mixin.0.8.7.jar:0.15.0+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:418) ~[sponge-mixin-0.15.0+mixin.0.8.7.jar:0.15.0+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.15.0+mixin.0.8.7.jar:0.15.0+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.15.0+mixin.0.8.7.jar:0.15.0+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.15.0+mixin.0.8.7.jar:0.15.0+mixin.0.8.7]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.16.0.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.16.0.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.0.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.0.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?]
        at java.lang.Class.privateGetDeclaredMethods(Class.java:3458) ~[?:?]
        at java.lang.Class.privateGetPublicMethods(Class.java:3483) ~[?:?]
        at java.lang.Class.privateGetPublicMethods(Class.java:3489) ~[?:?]
        at java.lang.Class.privateGetPublicMethods(Class.java:3489) ~[?:?]
        at java.lang.Class.privateGetPublicMethods(Class.java:3489) ~[?:?]
        at java.lang.Class.getMethods(Class.java:2068) ~[?:?]
        at com.mohistmc.banner.bukkit.remapping.ClassLoaderRemapper.tryGetMethods(ClassLoaderRemapper.java:109) ~[banner-1.20.1-608-server.jar:?]
        at com.mohistmc.banner.bukkit.remapping.ClassLoaderRemapper.lambda$getMethods$0(ClassLoaderRemapper.java:102) ~[banner-1.20.1-608-server.jar:?]
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1740) ~[?:?]
        at com.mohistmc.banner.bukkit.remapping.ClassLoaderRemapper.getMethods(ClassLoaderRemapper.java:102) ~[banner-1.20.1-608-server.jar:?]
        at com.mohistmc.banner.bukkit.remapping.ClassLoaderRemapper.tryMapMethodToSrg(ClassLoaderRemapper.java:223) ~[banner-1.20.1-608-server.jar:?]
        at com.mohistmc.banner.bukkit.remapping.ReflectionHandler_6.handleLookupFindStatic(ReflectionHandler.java:304) ~[banner-1.20.1-608-server.jar:?]
        at com.mohistmc.banner.bukkit.remapping.ReflectionHandler_6.handleLookupFindVirtual(ReflectionHandler.java:320) ~[banner-1.20.1-608-server.jar:?]
        at net.kyori.adventure.platform.bukkit.MinecraftReflection.searchMethod(MinecraftReflection.java:182) ~[?:?]
        at net.kyori.adventure.platform.bukkit.MinecraftReflection.searchMethod(MinecraftReflection.java:157) ~[?:?]
        at net.kyori.adventure.platform.bukkit.CraftBukkitAccess$Chat1_19_3.<clinit>(CraftBukkitAccess.java:95) ~[?:?]
        ... 27 more
[12:10:45] [Server thread/INFO]: [ImprovedFactions] Disabling ImprovedFactions v2.2.0
[12:10:45] [Server thread/ERROR]: Error occurred while disabling ImprovedFactions v2.2.0 (Is it up to date?)
kotlin.UninitializedPropertyAccessException: lateinit property adventure has not been initialized
        at io.github.toberocat.improvedfactions.ImprovedFactionsPlugin.getAdventure(ImprovedFactionsPlugin.kt:52) ~[?:?]
        at io.github.toberocat.improvedfactions.ImprovedFactionsPlugin.onDisable(ImprovedFactionsPlugin.kt:89) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:269) ~[banner-1.20.1-608-server.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:366) ~[banner-1.20.1-608-server.jar:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:504) ~[banner-1.20.1-608-server.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:341) ~[banner-1.20.1-608-server.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:482) ~[banner-1.20.1-608-server.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:537) ~[banner-1.20.1-608-server.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:459) ~[banner-1.20.1-608-server.jar:?]
        at net.minecraft.server.MinecraftServer.handler$zca000$banner$enablePlugins(MinecraftServer.java:2208) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:339) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3823(class_3176.java:169) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:2061) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]

**Expected behavior**
I thought the plugin was going to load.

**Version (please complete the following information):**
 - Plugin: ImprovedFaction-2.2.0
 - Server: Bukkit + Spigot + Fabric (= Banner). The server runs on Java 19.
 
Here is the link to the Banner website if you want it : https://mohistmc.com/software/banner

**Comment by ToberoCat** [comment]
I'll check it, but this has very low priority
