### ISSUE TITLE
[Bug] /f home error IllegalStateException: Not scheduled yet

### ISSUE THREAD

**Issue by Aeziak** [ToberoCat/ImprovedFactions#212]
Hello ! When I do /f home command, it's teleporting me to faction home after 5 seconds, but then it keeps teleporting with error in console.

```
[ImprovedFactions] Task #9730 for ImprovedFactions v2.2.0 generated an exception
java.lang.IllegalStateException: Not scheduled yet
        at org.bukkit.scheduler.BukkitRunnable.checkScheduled(BukkitRunnable.java:156) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.scheduler.BukkitRunnable.getTaskId(BukkitRunnable.java:150) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.scheduler.BukkitRunnable.cancel(BukkitRunnable.java:30) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at io.github.toberocat.improvedfactions.utils.PlayerTeleporter.cancel(PlayerTeleporter.kt:48) ~[ImprovedFactions-2.2.0.jar:?]
        at io.github.toberocat.improvedfactions.utils.PlayerTeleporter.run(PlayerTeleporter.kt:56) ~[ImprovedFactions-2.2.0.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-388]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.2.jar:git-Paper-388]
```

1.  /f sethome
2. Restart the server
3.  /f home
4.  Error should happen

**Version (please complete the following information):**
 - Plugin: ImprovedFaction 2.20
 - Server: Papermc 1.18.2

**Comment by ToberoCat** [comment]
As far as I know, I have already fixed it in the latest dev build. Please check this one out for a fix

**Comment by ToberoCat** [comment]
Alright, I confirmed it now. This bug will be fixed in a new version
