### ISSUE TITLE
[Bug] Dynmap is not showing the Faction Owner or Max Power

### ISSUE THREAD

**Issue by VvegteHD** [ToberoCat/ImprovedFactions#261]
**Describe the bug**
When I load into the Dynmap on my Minecraft server, the faction does not show the proper name of the owner or max power of said faction, instead it says:
Owner: %faction_owner%
Max Power: %faction_maxPower%

**Error log from console**
I have this in the console but unsure if it actually what is casing the issue. 

[21:54:08 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'factions' in plugin ImprovedFactions v2.2.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:999) ~[paper-1.20.4.jar:git-Paper-499]
        at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.20.4.jar:git-Paper-499]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31) ~[paper-1.20.4.jar:git-Paper-499]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[paper-1.20.4.jar:git-Paper-499]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[paper-1.20.4.jar:git-Paper-499]
        at net.minecraft.commands.execution.CommandQueueEntry.a(CommandQueueEntry.java:5) ~[paper-1.20.4.jar:git-Paper-499]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[paper-1.20.4.jar:git-Paper-499]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:434) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:336) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:323) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2230) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:2190) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.4.jar:git-Paper-499]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1465) ~[paper-1.20.4.jar:git-Paper-499]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[paper-1.20.4.jar:git-Paper-499]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:123) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1442) ~[paper-1.20.4.jar:git-Paper-499]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1365) ~[paper-1.20.4.jar:git-Paper-499]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:133) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1343) ~[paper-1.20.4.jar:git-Paper-499]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1232) ~[paper-1.20.4.jar:git-Paper-499]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-499]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassCastException: class io.github.toberocat.improvedfactions.invites.FactionInvite cannot be cast to class java.lang.Integer (io.github.toberocat.improvedfactions.invites.FactionInvite is in unnamed module of loader 'ImprovedFactions-2.2.0.jar' @3e755925; java.lang.Integer is in module java.base of loader 'bootstrap')
        at io.github.toberocat.improvedfactions.commands.invite.InviteDiscardCommand.handle(InviteDiscardCommand.kt:31) ~[ImprovedFactions-2.2.0.jar:?]
        at io.github.toberocat.improvedfactions.toberocore.command.PlayerSubCommand.handleCommand(PlayerSubCommand.java:29) ~[ImprovedFactions-2.2.0.jar:?]
        at io.github.toberocat.improvedfactions.toberocore.command.SubCommand.handleWithOptions(SubCommand.java:95) ~[ImprovedFactions-2.2.0.jar:?]
        at io.github.toberocat.improvedfactions.toberocore.command.SubCommand.routeCall(SubCommand.java:75) ~[ImprovedFactions-2.2.0.jar:?]
        at io.github.toberocat.improvedfactions.toberocore.command.CommandExecutor.onCommand(CommandExecutor.java:52) ~[ImprovedFactions-2.2.0.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        ... 29 more

**To Reproduce**
Unsure as it just immediately starts happening on the server when it starts. I did increase the faction max power but I don't see why that would have changed anything. 

**Expected behavior**
I would expect the dynmap to show the proper owner and power. 

**Screenshots**
![Screenshot (40)](https://github.com/user-attachments/assets/a5dc340c-6f57-4d67-92ca-3bd00d6f5a86)

**Version (please complete the following information):**
 - Plugin: ImprovedFactions - 2.2.0
 - Server: 1.20.4 Paper 

**Additional context**
If I need to provide more, I can attempt to do so.

**Comment by ToberoCat** [comment]
Will be fixed with 2.3.0.67 builds
