### ISSUE TITLE
/f settings some icons are broken and break the gui

### ISSUE THREAD

**Issue by xcomcadx** [ToberoCat/ImprovedFactions#32]
**Describe the bug**

rename faction MOTD and set tag in /f settings all throw back errors and freeze the gui. i think its something to do with the anvil text box. happens even when i block it in settings.yml

**Error log from console**
java.lang.NoSuchMethodError: 'net.minecraft.world.entity.player.PlayerInventory net.minecraft.server.level.EntityPlayer.fB()'
        at net.wesjd.anvilgui.version.Wrapper1_19_R1$AnvilContainer.<init>(Wrapper1_19_R1.java:88) ~[ImprovedFactionsV1.5.jar:?]
        at net.wesjd.anvilgui.version.Wrapper1_19_R1.newContainerAnvil(Wrapper1_19_R1.java:82) ~[ImprovedFactionsV1.5.jar:?]
        at net.wesjd.anvilgui.AnvilGUI.openInventory(AnvilGUI.java:177) ~[ImprovedFactionsV1.5.jar:?]
        at net.wesjd.anvilgui.AnvilGUI.<init>(AnvilGUI.java:165) ~[ImprovedFactionsV1.5.jar:?]
        at net.wesjd.anvilgui.AnvilGUI.<init>(AnvilGUI.java:30) ~[ImprovedFactionsV1.5.jar:?]
        at net.wesjd.anvilgui.AnvilGUI$Builder.open(AnvilGUI.java:491) ~[ImprovedFactionsV1.5.jar:?]
        at io.github.toberocat.core.utility.settings.SettingActions.renameFaction(SettingActions.java:43) ~[ImprovedFactionsV1.5.jar:?]
        at io.github.toberocat.core.utility.settings.type.CallbackSettings.execute(CallbackSettings.java:23) ~[ImprovedFactionsV1.5.jar:?]
        at io.github.toberocat.core.utility.settings.type.Setting$3.lambda$OnClick$0(Setting.java:173) ~[ImprovedFactionsV1.5.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-132]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.2.jar:git-Paper-132]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1493) ~[paper-1.19.2.jar:git-Paper-132]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.2.jar:git-Paper-132]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1417) ~[paper-1.19.2.jar:git-Paper-132]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1193) ~[paper-1.19.2.jar:git-Paper-132]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-132]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**To Reproduce**
1. Go to '/f settings'
2. Click on 'RENAME, MOTD, or Set tag'

**Expected behavior**
you are now able to drag around items in gui and none of them work anymore when you click on them.

**Screenshots**

**Version (please complete the following information):**
 - Plugin: improved factions 1.5
 - Server: paper

**Additional context**

**Comment by ToberoCat** [comment]
Issue has been fixed with 2.x.x builds
