### ISSUE TITLE
[Bug] Name change error

### ISSUE THREAD

**Issue by anarix0** [ToberoCat/ImprovedFactions#55]
**Describe the bug**
When you try to change factions name, motd or tag it doesn't work

**Error log from console**
[ImprovedFactions] Task #432 for ImprovedFactions v1.5 generated an exception
java.lang.NoSuchMethodError: 'net.minecraft.world.entity.player.PlayerInventory net.minecraft.server.level.EntityPlayer.fB()'
	at net.wesjd.anvilgui.version.Wrapper1_19_R1$AnvilContainer.<init>(Wrapper1_19_R1.java:88) ~[ImprovedFactionsV1.5.jar:?]
	at net.wesjd.anvilgui.version.Wrapper1_19_R1.newContainerAnvil(Wrapper1_19_R1.java:82) ~[ImprovedFactionsV1.5.jar:?]
	at net.wesjd.anvilgui.AnvilGUI.openInventory(AnvilGUI.java:177) ~[ImprovedFactionsV1.5.jar:?]
	at net.wesjd.anvilgui.AnvilGUI.<init>(AnvilGUI.java:165) ~[ImprovedFactionsV1.5.jar:?]
	at net.wesjd.anvilgui.AnvilGUI.<init>(AnvilGUI.java:30) ~[ImprovedFactionsV1.5.jar:?]
	at net.wesjd.anvilgui.AnvilGUI$Builder.open(AnvilGUI.java:491) ~[ImprovedFactionsV1.5.jar:?]
	at io.github.toberocat.core.utility.settings.SettingActions.renameFaction(SettingActions.java:43) ~[ImprovedFactionsV1.5.jar:?]
	at io.github.toberocat.core.utility.settings.type.CallbackSettings.execute(CallbackSettings.java:23) ~[ImprovedFactionsV1.5.jar:?]
	at io.github.toberocat.core.utility.settings.type.Setting$3.lambda$OnClick$0(Setting.java:173) ~[ImprovedFactionsV1.5.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-214]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.2.jar:git-Paper-214]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1473) ~[paper-1.19.2.jar:git-Paper-214]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.2.jar:git-Paper-214]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.2.jar:git-Paper-214]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.2.jar:git-Paper-214]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-214]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**To Reproduce**
1. Go to '/f settings'
2. Click on 'Set MOTD'
3. See error

**Expected behavior**
Change the faction motd

**Version (please complete the following information):**
 - Plugin: https://www.spigotmc.org/resources/improved-factions.95617/
 - Server: 1.19.2 PaperMC

**Comment by ToberoCat** [comment]
Try using this version: https://cdn.discordapp.com/attachments/1023861830495506482/1023861877786292275/ImprovedFactionsV1.5.1.jar

This is a link to the discord server where I posted the file. It contains some bug fixes, which includes the anvil gui

**Comment by ToberoCat** [comment]
Has been fixed with 2.x.x builds
